SELECT b.AUTHOR_ID, a.AUTHOR_NAME, b.CATEGORY, 
SUM(b.PRICE * bs.SALES) AS TOTAL_SALES
FROM BOOK b join AUTHOR a ON b.AUTHOR_ID = a.AUTHOR_ID
join BOOK_SALES bs ON bs.BOOK_ID = b.BOOK_ID
WHERE bs.SALES_DATE LIKE '2022-01%'
GROUP BY AUTHOR_NAME, CATEGORY
ORDER BY b.AUTHOR_ID, b.CATEGORY DESC