SELECT TO_CHAR(SALES_DATE, 'YYYY-MM-DD') AS SALES_DATE, PRODUCT_ID, USER_ID, SALES_AMOUNT
FROM (
    SELECT l.SALES_DATE, l.PRODUCT_ID, l.USER_ID, l.SALES_AMOUNT
    FROM ONLINE_SALE l
    WHERE l.SALES_DATE BETWEEN DATE '2022-03-01' AND DATE '2022-03-31'
    UNION ALL
    SELECT f.SALES_DATE, f.PRODUCT_ID, NULL AS USER_ID, f.SALES_AMOUNT
    FROM OFFLINE_SALE f
    WHERE f.SALES_DATE BETWEEN DATE '2022-03-01' AND DATE '2022-03-31'
)
ORDER BY SALES_DATE, PRODUCT_ID, USER_ID;
