SELECT DISTINCT c.CAR_ID, 
                c.CAR_TYPE, 
                TRUNC((c.DAILY_FEE * (100 - p.DISCOUNT_RATE) / 100) * 30, 0) AS FEE
FROM CAR_RENTAL_COMPANY_CAR c
LEFT JOIN CAR_RENTAL_COMPANY_DISCOUNT_PLAN p 
    ON c.CAR_TYPE = p.CAR_TYPE 
    AND p.DURATION_TYPE = '30일 이상'
WHERE c.CAR_TYPE IN ('세단', 'SUV')
  AND NOT EXISTS (
      SELECT 1 
      FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY h
      WHERE h.CAR_ID = c.CAR_ID
        AND h.START_DATE <= TO_DATE('2022-11-30', 'YYYY-MM-DD')
        AND h.END_DATE >= TO_DATE('2022-11-01', 'YYYY-MM-DD')
  )
  AND 500000 <= (c.DAILY_FEE * (100 - p.DISCOUNT_RATE) / 100) * 30
  AND (c.DAILY_FEE * (100 - p.DISCOUNT_RATE) / 100) * 30 < 2000000
ORDER BY FEE DESC, c.CAR_TYPE ASC, c.CAR_ID DESC;
