WITH TOTAL_INFO AS (
    SELECT u.USER_ID, u.GENDER, u.AGE, s.ONLINE_SALE_ID, 
    s.PRODUCT_ID, s.SALES_AMOUNT, s.SALES_DATE 
    FROM USER_INFO u join ONLINE_SALE s
    ON u.USER_ID = s.USER_ID
    WHERE u.GENDER IS NOT NULL
)
SELECT TO_CHAR(SALES_DATE, 'yyyy') AS YEAR, TO_CHAR(SALES_DATE, 'fmmm') AS MONTH, GENDER, COUNT(DISTINCT USER_ID) AS USERS
FROM TOTAL_INFO
GROUP BY TO_CHAR(SALES_DATE, 'yyyy'), TO_CHAR(SALES_DATE, 'fmmm'), GENDER
ORDER BY YEAR, TO_NUMBER(MONTH), GENDER