SELECT TO_CHAR(SALES_DATE,'YYYY') AS YEAR, TO_CHAR(SALES_DATE, 'FMMM') AS MONTH, 
COUNT(DISTINCT USER_ID) AS PURCHASED_USERS, ROUND(COUNT(DISTINCT USER_ID)/(SELECT COUNT(DISTINCT USER_ID) FROM USER_INFO WHERE TO_CHAR(JOINED,'YYYY-MM-DD') LIKE '2021%'), 1) AS PUCHASED_RATIO
FROM ONLINE_SALE
WHERE USER_ID IN (SELECT USER_ID 
                  FROM USER_INFO
                  WHERE TO_CHAR(JOINED,'YYYY-MM-DD') LIKE '2021%')
GROUP BY TO_CHAR(SALES_DATE,'YYYY'), TO_CHAR(SALES_DATE, 'FMMM')
ORDER BY TO_NUMBER(YEAR), TO_NUMBER(MONTH)