SELECT ch.HISTORY_ID, 
CASE 
    WHEN ch.gap >= 90 THEN 
        (ch.DAILY_FEE - (ch.DAILY_FEE * 0.01 * (SELECT DISCOUNT_RATE FROM CAR_RENTAL_COMPANY_DISCOUNT_PLAN WHERE DURATION_TYPE = '90일 이상' AND CAR_TYPE = '트럭'))) * ch.gap
    WHEN ch.gap >= 30 THEN 
        (ch.DAILY_FEE - (ch.DAILY_FEE * 0.01 * (SELECT DISCOUNT_RATE FROM CAR_RENTAL_COMPANY_DISCOUNT_PLAN WHERE DURATION_TYPE = '30일 이상' AND CAR_TYPE = '트럭'))) * ch.gap
    WHEN ch.gap >= 7 THEN 
        (ch.DAILY_FEE - (ch.DAILY_FEE * 0.01 * (SELECT DISCOUNT_RATE FROM CAR_RENTAL_COMPANY_DISCOUNT_PLAN WHERE DURATION_TYPE = '7일 이상' AND CAR_TYPE = '트럭'))) * ch.gap
    ELSE 
        ch.DAILY_FEE * ch.gap
END AS FEE
FROM (
    SELECT c.CAR_ID, c.DAILY_FEE, (h.END_DATE - h.START_DATE+1) AS gap, h.HISTORY_ID  
    FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY h 
    JOIN CAR_RENTAL_COMPANY_CAR c ON h.CAR_ID = c.CAR_ID 
    WHERE c.CAR_TYPE = '트럭'
) ch 
ORDER BY FEE DESC, ch.HISTORY_ID DESC;
