SELECT t.HOUR AS HOUR, COUNT(o.HOUR) AS COUNT
FROM (SELECT TO_CHAR(DATETIME,'FMHH24') AS HOUR FROM ANIMAL_OUTS) o
RIGHT OUTER JOIN 
(SELECT ROWNUM-1 AS HOUR FROM DUAL CONNECT BY LEVEL <= 24) t
ON o.HOUR = t.HOUR
GROUP BY t.HOUR
ORDER BY t.HOUR
