SELECT u.USER_ID, u.NICKNAME, sum(b.PRICE) AS TOTAL_SALES
FROM USED_GOODS_BOARD b join USED_GOODS_USER u
ON b.WRITER_ID = u.USER_ID
WHERE b.STATUS = 'DONE' 
GROUP BY b.WRITER_ID
HAVING sum(b.PRICE) >= 700000
ORDER BY TOTAL_SALES;