WITH MaxPrices AS (
    SELECT CATEGORY, MAX(PRICE) AS MAX_PRICE
    FROM FOOD_PRODUCT
    WHERE CATEGORY IN ('과자','국','김치','식용유')
    GROUP BY CATEGORY
)
SELECT m.CATEGORY, m.MAX_PRICE, f.PRODUCT_NAME
FROM FOOD_PRODUCT f JOIN MaxPrices m
ON f.CATEGORY = m.CATEGORY AND f.PRICE = m.MAX_PRICE
ORDER BY f.PRICE DESC